# Checkov configuration
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Only scan Terraform files
framework:
  - terraform

# Compact output
compact: true

# Skip checks that don't apply to this infrastructure type
skip-check:
  # We're using Cloudflare Email Routing, not a full mail server
  - CKV2_AWS_SKIP  # AWS-specific checks (we use Cloudflare)
  
# Check severity threshold
# soft-fail: true  # Don't fail the build (set in workflow)
